name: Terraform CI

on:
  push:
    branches:
      - feature/pipeline

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Env_prod

    env:
      ARM_CLIENT_ID: 53d32f59-988d-40ea-892f-9b983abd8f8a
      ARM_CLIENT_SECRET: Ja68Q~8z8Bwdtl93dpgtexiZDyNSXxTKxtFN7cpG
      ARM_SUBSCRIPTION_ID: 1901e74c-f287-4ad5-a027-7e82572afe7a
      ARM_TENANT_ID: ce1221be-2dd4-4dbd-be67-4765d692baf9

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        run: |
          az login --service-principal \
            -u "53d32f59-988d-40ea-892f-9b983abd8f8a" \
            -p "Ja68Q~8z8Bwdtl93dpgtexiZDyNSXxTKxtFN7cpG" \
            --tenant "ce1221be-2dd4-4dbd-be67-4765d692baf9"

      - name: Set Subscription
        run: |
          az account set --subscription "1901e74c-f287-4ad5-a027-7e82572afe7a"

      - name: Terraform Version
        run: terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      -  name: Upload Terraform Plan
  uses: actions/upload-artifact@v4
  with:
    name: tfplan
    path: Env_prod/tfplan

  terraform-apply:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Env_prod

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login --service-principal \
            -u "53d32f59-988d-40ea-892f-9b983abd8f8a" \
            -p "Ja68Q~8z8Bwdtl93dpgtexiZDyNSXxTKxtFN7cpG" \
            --tenant "ce1221be-2dd4-4dbd-be67-4765d692baf9"

      - run: terraform init

      - run: terraform apply -auto-approve